### ISSUE TITLE
compile cita-cli, report error: use of deprecated item 'protobuf

### ISSUE THREAD

**Issue by myfreshcity** [citahub/cita-cli#138]
when run $ cargo install --path .
some error occur below:
Installing cita-cli v20.2.2 (/Users/tom/Downloads/cita-cli/cita-cli)
    Updating crates.io index
   Compiling cita-tool v0.19.0 (/Users/tom/Downloads/cita-cli/cita-tool)
error: use of deprecated item 'protobuf::lazy::ONCE_INIT': Regenerate .proto files to use safer initializer
   --> cita-tool/src/protos/blockchain.rs:162:19
    |
162 |             lock: ::protobuf::lazy::ONCE_INIT,
    |                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
note: lint level defined here
   --> cita-tool/src/lib.rs:3:9
    |
3   | #![deny(warnings)]
    |         ^^^^^^^^
    = note: `#[deny(deprecated)]` implied by `#[deny(warnings)]`

error: use of deprecated item 'protobuf::lazy::ONCE_INIT': Regenerate .proto files to use safer initializer
   --> cita-tool/src/protos/blockchain.rs:189:19
    |
189 |             lock: ::protobuf::lazy::ONCE_INIT,
    |                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: use of deprecated item 'protobuf::lazy::ONCE_INIT': Regenerate .proto files to use safer initializer
   --> cita-tool/src/protos/blockchain.rs:642:19
    |
642 |             lock: ::protobuf::lazy::ONCE_INIT,
    |                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: use of deprecated item 'protobuf::lazy::ONCE_INIT': Regenerate .proto files to use safer initializer
   --> cita-tool/src/protos/blockchain.rs:709:19
    |
709 |             lock: ::protobuf::lazy::ONCE_INIT,
    |                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: use of deprecated item 'protobuf::lazy::ONCE_INIT': Regenerate .proto files to use safer initializer
   --> cita-tool/src/protos/blockchain.rs:888:19
    |
888 |             lock: ::protobuf::lazy::ONCE_INIT,
    |                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: use of deprecated item 'protobuf::lazy::ONCE_INIT': Regenerate .proto files to use safer initializer
   --> cita-tool/src/protos/blockchain.rs:915:19
    |
915 |             lock: ::protobuf::lazy::ONCE_INIT,
    |                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: use of deprecated item 'protobuf::lazy::ONCE_INIT': Regenerate .proto files to use safer initializer
    --> cita-tool/src/protos/blockchain.rs:1081:19
     |
1081 |             lock: ::protobuf::lazy::ONCE_INIT,
     |                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: use of deprecated item 'protobuf::lazy::ONCE_INIT': Regenerate .proto files to use safer initializer
    --> cita-tool/src/protos/blockchain.rs:1108:19
     |
1108 |             lock: ::protobuf::lazy::ONCE_INIT,
     |                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: use of deprecated item 'protobuf::lazy::ONCE_INIT': Regenerate .proto files to use safer initializer
    --> cita-tool/src/protos/blockchain.rs:1372:19
     |
1372 |             lock: ::protobuf::lazy::ONCE_INIT,
     |                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: use of deprecated item 'protobuf::lazy::ONCE_INIT': Regenerate .proto files to use safer initializer
    --> cita-tool/src/protos/blockchain.rs:1414:19
     |
1414 |             lock: ::protobuf::lazy::ONCE_INIT,
     |                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: use of deprecated item 'protobuf::lazy::ONCE_INIT': Regenerate .proto files to use safer initializer
    --> cita-tool/src/protos/blockchain.rs:1855:19
     |
1855 |             lock: ::protobuf::lazy::ONCE_INIT,
     |                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: use of deprecated item 'protobuf::lazy::ONCE_INIT': Regenerate .proto files to use safer initializer
    --> cita-tool/src/protos/blockchain.rs:1922:19
     |
1922 |             lock: ::protobuf::lazy::ONCE_INIT,
     |                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: use of deprecated item 'protobuf::lazy::ONCE_INIT': Regenerate .proto files to use safer initializer
    --> cita-tool/src/protos/blockchain.rs:2148:19
     |
2148 |             lock: ::protobuf::lazy::ONCE_INIT,
     |                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: use of deprecated item 'protobuf::lazy::ONCE_INIT': Regenerate .proto files to use safer initializer
    --> cita-tool/src/protos/blockchain.rs:2180:19
     |
2180 |             lock: ::protobuf::lazy::ONCE_INIT,
     |                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: use of deprecated item 'protobuf::lazy::ONCE_INIT': Regenerate .proto files to use safer initializer
    --> cita-tool/src/protos/blockchain.rs:2410:19
     |
2410 |             lock: ::protobuf::lazy::ONCE_INIT,
     |                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: use of deprecated item 'protobuf::lazy::ONCE_INIT': Regenerate .proto files to use safer initializer
    --> cita-tool/src/protos/blockchain.rs:2442:19
     |
2442 |             lock: ::protobuf::lazy::ONCE_INIT,
     |                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: use of deprecated item 'protobuf::lazy::ONCE_INIT': Regenerate .proto files to use safer initializer
    --> cita-tool/src/protos/blockchain.rs:2592:19
     |
2592 |             lock: ::protobuf::lazy::ONCE_INIT,
     |                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: use of deprecated item 'protobuf::lazy::ONCE_INIT': Regenerate .proto files to use safer initializer
    --> cita-tool/src/protos/blockchain.rs:2614:19
     |
2614 |             lock: ::protobuf::lazy::ONCE_INIT,
     |                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: use of deprecated item 'protobuf::lazy::ONCE_INIT': Regenerate .proto files to use safer initializer
    --> cita-tool/src/protos/blockchain.rs:2850:19
     |
2850 |             lock: ::protobuf::lazy::ONCE_INIT,
     |                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: use of deprecated item 'protobuf::lazy::ONCE_INIT': Regenerate .proto files to use safer initializer
    --> cita-tool/src/protos/blockchain.rs:2882:19
     |
2882 |             lock: ::protobuf::lazy::ONCE_INIT,
     |                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: use of deprecated item 'protobuf::lazy::ONCE_INIT': Regenerate .proto files to use safer initializer
    --> cita-tool/src/protos/blockchain.rs:3091:19
     |
3091 |             lock: ::protobuf::lazy::ONCE_INIT,
     |                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: use of deprecated item 'protobuf::lazy::ONCE_INIT': Regenerate .proto files to use safer initializer
    --> cita-tool/src/protos/blockchain.rs:3118:19
     |
3118 |             lock: ::protobuf::lazy::ONCE_INIT,
     |                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: use of deprecated item 'protobuf::lazy::ONCE_INIT': Regenerate .proto files to use safer initializer
    --> cita-tool/src/protos/blockchain.rs:3304:19
     |
3304 |             lock: ::protobuf::lazy::ONCE_INIT,
     |                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: use of deprecated item 'protobuf::lazy::ONCE_INIT': Regenerate .proto files to use safer initializer
    --> cita-tool/src/protos/blockchain.rs:3331:19
     |
3331 |             lock: ::protobuf::lazy::ONCE_INIT,
     |                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: use of deprecated item 'protobuf::lazy::ONCE_INIT': Regenerate .proto files to use safer initializer
    --> cita-tool/src/protos/blockchain.rs:3507:19
     |
3507 |             lock: ::protobuf::lazy::ONCE_INIT,
     |                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: use of deprecated item 'protobuf::lazy::ONCE_INIT': Regenerate .proto files to use safer initializer
    --> cita-tool/src/protos/blockchain.rs:3534:19
     |
3534 |             lock: ::protobuf::lazy::ONCE_INIT,
     |                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: use of deprecated item 'protobuf::lazy::ONCE_INIT': Regenerate .proto files to use safer initializer
    --> cita-tool/src/protos/blockchain.rs:3669:19
     |
3669 |             lock: ::protobuf::lazy::ONCE_INIT,
     |                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: use of deprecated item 'protobuf::lazy::ONCE_INIT': Regenerate .proto files to use safer initializer
    --> cita-tool/src/protos/blockchain.rs:3691:19
     |
3691 |             lock: ::protobuf::lazy::ONCE_INIT,
     |                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: use of deprecated item 'protobuf::lazy::ONCE_INIT': Regenerate .proto files to use safer initializer
    --> cita-tool/src/protos/blockchain.rs:3751:19
     |
3751 |             lock: ::protobuf::lazy::ONCE_INIT,
     |                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: use of deprecated item 'protobuf::lazy::ONCE_INIT': Regenerate .proto files to use safer initializer
    --> cita-tool/src/protos/blockchain.rs:3806:19
     |
3806 |             lock: ::protobuf::lazy::ONCE_INIT,
     |                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: use of deprecated item 'protobuf::lazy::ONCE_INIT': Regenerate .proto files to use safer initializer
    --> cita-tool/src/protos/blockchain.rs:4077:11
     |
4077 |     lock: ::protobuf::lazy::ONCE_INIT,
     |           ^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: use of deprecated item 'protobuf::reflect::message::MessageDescriptor::new': Please regenerate .rs files from .proto files to use newer APIs
   --> cita-tool/src/protos/blockchain.rs:178:17
    |
178 |                 ::protobuf::reflect::MessageDescriptor::new::<Proof>(
    |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: use of deprecated item 'protobuf::reflect::message::MessageDescriptor::new': Please regenerate .rs files from .proto files to use newer APIs
   --> cita-tool/src/protos/blockchain.rs:698:17
    |
698 |                 ::protobuf::reflect::MessageDescriptor::new::<BlockHeader>(
    |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: use of deprecated item 'protobuf::reflect::message::MessageDescriptor::new': Please regenerate .rs files from .proto files to use newer APIs
   --> cita-tool/src/protos/blockchain.rs:904:17
    |
904 |                 ::protobuf::reflect::MessageDescriptor::new::<Status>(
    |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: use of deprecated item 'protobuf::reflect::message::MessageDescriptor::new': Please regenerate .rs files from .proto files to use newer APIs
    --> cita-tool/src/protos/blockchain.rs:1097:17
     |
1097 |                 ::protobuf::reflect::MessageDescriptor::new::<AccountGasLimit>(
     |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: use of deprecated item 'protobuf::reflect::message::MessageDescriptor::new': Please regenerate .rs files from .proto files to use newer APIs
    --> cita-tool/src/protos/blockchain.rs:1403:17
     |
1403 |                 ::protobuf::reflect::MessageDescriptor::new::<RichStatus>(
     |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: use of deprecated item 'protobuf::reflect::message::MessageDescriptor::new': Please regenerate .rs files from .proto files to use newer APIs
    --> cita-tool/src/protos/blockchain.rs:1911:17
     |
1911 |                 ::protobuf::reflect::MessageDescriptor::new::<Transaction>(
     |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: use of deprecated item 'protobuf::reflect::message::MessageDescriptor::new': Please regenerate .rs files from .proto files to use newer APIs
    --> cita-tool/src/protos/blockchain.rs:2169:17
     |
2169 |                 ::protobuf::reflect::MessageDescriptor::new::<UnverifiedTransaction>(
     |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: use of deprecated item 'protobuf::reflect::message::MessageDescriptor::new': Please regenerate .rs files from .proto files to use newer APIs
    --> cita-tool/src/protos/blockchain.rs:2431:17
     |
2431 |                 ::protobuf::reflect::MessageDescriptor::new::<SignedTransaction>(
     |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: use of deprecated item 'protobuf::reflect::message::MessageDescriptor::new': Please regenerate .rs files from .proto files to use newer APIs
    --> cita-tool/src/protos/blockchain.rs:2603:17
     |
2603 |                 ::protobuf::reflect::MessageDescriptor::new::<BlockBody>(
     |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: use of deprecated item 'protobuf::reflect::message::MessageDescriptor::new': Please regenerate .rs files from .proto files to use newer APIs
    --> cita-tool/src/protos/blockchain.rs:2871:17
     |
2871 |                 ::protobuf::reflect::MessageDescriptor::new::<Block>(
     |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: use of deprecated item 'protobuf::reflect::message::MessageDescriptor::new': Please regenerate .rs files from .proto files to use newer APIs
    --> cita-tool/src/protos/blockchain.rs:3107:17
     |
3107 |                 ::protobuf::reflect::MessageDescriptor::new::<BlockWithProof>(
     |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: use of deprecated item 'protobuf::reflect::message::MessageDescriptor::new': Please regenerate .rs files from .proto files to use newer APIs
    --> cita-tool/src/protos/blockchain.rs:3320:17
     |
3320 |                 ::protobuf::reflect::MessageDescriptor::new::<BlockTxs>(
     |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: use of deprecated item 'protobuf::reflect::message::MessageDescriptor::new': Please regenerate .rs files from .proto files to use newer APIs
    --> cita-tool/src/protos/blockchain.rs:3523:17
     |
3523 |                 ::protobuf::reflect::MessageDescriptor::new::<BlackList>(
     |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: use of deprecated item 'protobuf::reflect::message::MessageDescriptor::new': Please regenerate .rs files from .proto files to use newer APIs
    --> cita-tool/src/protos/blockchain.rs:3680:17
     |
3680 |                 ::protobuf::reflect::MessageDescriptor::new::<StateSignal>(
     |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: use of deprecated item 'protobuf::reflect::enums::EnumDescriptor::new': Please regenerate .rs files from .proto files to use newer APIs
    --> cita-tool/src/protos/blockchain.rs:3756:17
     |
3756 |                 ::protobuf::reflect::EnumDescriptor::new("ProofType", file_descriptor_proto())
     |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: use of deprecated item 'protobuf::reflect::enums::EnumDescriptor::new': Please regenerate .rs files from .proto files to use newer APIs
    --> cita-tool/src/protos/blockchain.rs:3811:17
     |
3811 |                 ::protobuf::reflect::EnumDescriptor::new("Crypto", file_descriptor_proto())
     |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: aborting due to 47 previous errors

error: failed to compile `cita-cli v20.2.2 (/Users/tom/Downloads/cita-cli/cita-cli)`, intermediate artifacts can be found at `/Users/tom/Downloads/cita-cli/target`

Caused by:
  could not compile `cita-tool`.

can give me some advice, thanks.

**Comment by rink1969** [comment]
https://github.com/citahub/cita-cli/pull/139
